[build]
  command = ""
  publish = "public"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/track"
  to = "/track.html"
  status = 200

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/refund-policy"
  to = "/refund-policy.html"
  status = 200

[[redirects]]
  from = "/return-policy"
  to = "/return-policy.html"
  status = 200

[[redirects]]
  from = "/disclaimer"
  to = "/disclaimer.html"
  status = 200
